### ISSUE TITLE
[bug] config files & messages need 2 safes after editing something one after another

### ISSUE THREAD

**Issue by etherealshini** [SCNetwork/scnx-issues#12]
### Description
u need to safe something twice after u edit something one after another

### How-To-Reproduce
1. open a module 
2. edit something (messages or toggles) twice

### Pictures
https://user-images.githubusercontent.com/73320261/156655621-73e58427-af61-4877-9786-dfacebc6d4c3.mp4
https://user-images.githubusercontent.com/73320261/156655631-5a2374ae-04fa-44ad-963e-d667c04f00b9.mp4

### Browser

Chrome 99 on Windows 10

**Comment by SCDerox** [comment]
Fixed hopefully, please comment if you run into similar issues, thanks for your report :+1:
