### ISSUE TITLE
[bug] Speichern Nicht möglich 

### ISSUE THREAD

**Issue by EnergyPlayYT** [SCNetwork/scnx-issues#13]
### Es ist schwierig die Konfiguration/Änderung zu speichern da das down menu es verdeckt
Stand: 12.03.2022 20:43 
Samsung note 20 

### How-To-Reproduce

1. Bot Modul öffnen 
2. Module öffnen 
3. änderungen auswählen 
4. speichern ist bedeckt durch das down menu

### Pictures
https://ibb.co/NsJtsjJ

### Browser
- Google Chrome 
--> Chrome 99 on Android 12

**Comment by SCDerox** [comment]
Fixed, thanks for your report :+1:
