### ISSUE TITLE
[bug] pressing on "issues" at the custom-bot dashboard will create an application-error

### ISSUE THREAD

**Issue by lunaxiie** [SCNetwork/scnx-issues#4]
### Description
When clicking on "issues" at the custombot dashboard u get an application error on scnx.app aka. the SCNX V2 Dashboard

### How-To-Reproduce

1. open the dashboard
2. go to custombot
3. press on issues
4. and u will see "Application error: a client-side exception has occurred (see the browser console for more information)."

### Pictures
![grafik](https://user-images.githubusercontent.com/73320261/153810200-5266fdbc-c859-4b38-a433-3d4423701b5c.png)
![grafik](https://user-images.githubusercontent.com/73320261/153810501-f23f3673-f5e1-4aaa-933a-56a5ca45f464.png)

### Browser
1) Chrome 98 on Windows 10

**Comment by SCDerox** [comment]
Can't reproduce on prod, chrome (chrome os)

**Comment by SCDerox** [comment]
Possible failing condition identified. Conf may not be existent under circumstances.

**Comment by SCDerox** [comment]
Possibly fixed, could you try again, @lunaxiie?

**Comment by lunaxiie** [comment]
> Possibly fixed, could you try again, @lunaxiie?

Sure, when I'm home I'm trying it 👍
