### ISSUE TITLE
[bug] messageeditor

### ISSUE THREAD

**Issue by lunaxiie** [SCNetwork/scnx-issues#6]
### Description
MessageEditor isn't loading the images correctly (or smth. like that)

### How-To-Reproduce
1. open the dashboard on scnx.app
2. click on custombot and choose modules
3. choose any module with an customizable embedmaker or messageeditor
4. put in some emojis, banners, images etc.

### Pictures
![grafik](https://user-images.githubusercontent.com/73320261/153884968-30366b31-bb9b-4721-b210-af3f6f57253b.png)

### Browser

Chrome 98 on Windows 10

**Comment by lunaxiie** [comment]
experienced the same in "bot-log-in" 
![grafik](https://user-images.githubusercontent.com/73320261/153886568-59f973ff-314e-4474-9cb9-9a7377784570.png)
(just wanted to add the note 👍)

**Comment by SCDerox** [comment]
fixed :+1:
