### ISSUE TITLE
[bug] messageeditor u can't edit the optional values on the selfroles element

### ISSUE THREAD

**Issue by blessinthefall** [SCNetwork/scnx-issues#8]
### How-To-Reproduce
1. click on any module 
2. choose a module with editable embeds
3. create an embed
4. try to add the "selfroles element" 

### Pictures
![grafik](https://user-images.githubusercontent.com/73320261/154649679-1f0211dd-4fa7-46e1-b858-b388ab7119d9.png)

### Browser

Chrome 98 on Windows 10

**Comment by SCDerox** [comment]
You can't enter a value less than the amount of role elements or more than this amount.
