### ISSUE TITLE
[bug] messageeditor isn't saving message component values

### ISSUE THREAD

**Issue by blessinthefall** [SCNetwork/scnx-issues#9]
### Description
when i'm trying to create selfroles the bot doesn't saves message component values, which means when u type "1" into the value, it makes the maximum amount from the roles to choose

### How-To-Reproduce
1. go to bot-log-in
2. create an embed
3. add the selfroles thing

### Pictures

https://user-images.githubusercontent.com/73320261/154765423-bdef9e6d-0d28-4977-8b7a-998238d91840.mp4

### Browser

Chrome 98 von Windows 10

**Comment by SCDerox** [comment]
Should be fixed; please update your custombot to the newest version :+1:
